### ISSUE TITLE
Scraping and Get meal from pdf files

### ISSUE THREAD

**Issue by Nusk-Rbb** [Nusk-Rbb/Dorm-Meal-Tracker#1]
# Tasks

## Scraping
- [x] get html file 
- [x] extract pdf links
- [x] download pdf files

## Extract Meals

- [x] PDF to Tables on csv file
- [ ] extract meals
- [ ] extract calotiries, etc...
